Add failing test for --edit-map cmdline option
Running "python run_uh.py --edit-map development" on the command line
yields:

    Error: 'development' is not a valid Unknown Horizons map or savegame file.

Broken by the fix for #2507