Fix crash when exiting game while buildtool is active
When the pause menu is activated via hotkey, the mouse tool stayed
active. Quitting the game then caused this crash:

    Traceback (most recent call last):
     File "/usr/lib/python2.7/site-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
        self._callback()
     File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 83, in real_callback
        callback(*args,**kwargs)
     File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 173, in delayed_f
        f( event )
     File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 351, in captured_f
        tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
     File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 60, in applyOnlySuitable
        return func(*args,**kwargs)
     File "/home/unknown-horizons/horizons/gui/modules/pausemenu.py", line 90, in _do_quit
        self._session.quit()
     File "/home/unknown-horizons/horizons/session.py", line 198, in quit
        self.end()
     File "/home/unknown-horizons/horizons/session.py", line 174, in end
        self.ingame_gui = None # keep this before world
     File "/home/unknown-horizons/horizons/util/living.py", line 63, in __set__
        self.__value.end()
     File "/home/unknown-horizons/horizons/gui/ingamegui.py", line 195, in end
        self.cursor.remove()
     File "/home/unknown-horizons/horizons/gui/mousetools/buildingtool.py", line 195, in remove
        self.session.ingame_gui.resource_overview.close_construction_mode()
    AttributeError: 'NoneType' object has no attribute 'close_construction_mode'

This is fixed by resetting the cursor when the pause menu is toggled.
However another problem surfaced:

    Traceback (most recent call last):
      File "run_uh.py", line 382, in <module>
        main()
      File "run_uh.py", line 191, in main
        ret = horizons.main.start(options)
      File "/home/reiner/projekte/uh/unknown-horizons/horizons/main.py", line 281, in start
        horizons.globals.fife.run()
      File "/home/reiner/projekte/uh/unknown-horizons/horizons/engine/engine.py", line 278, in run
        self.loop()
      File "/home/reiner/projekte/uh/unknown-horizons/horizons/engine/engine.py", line 290, in loop
        f()
      File "/home/reiner/projekte/uh/unknown-horizons/horizons/extscheduler.py", line 72, in tick
        obj.callback()
      File "/home/reiner/projekte/uh/unknown-horizons/horizons/gui/mousetools/navigationtool.py", line 263, in _send_hover_instance_upate
        instances = set(self.get_hover_instances(where))
      File "/home/reiner/projekte/uh/unknown-horizons/tests/gui/helper.py", line 141, in wrapped
        screen_point = self.session.view.cam.toScreenCoordinates(fife.ExactModelCoordinate(evt.getX(), evt.getY()))
    AttributeError: 'NoneType' object has no attribute 'cam'

When the navigation tool is activated, a callback is added to check for
hover instances or something. When the game is exited too quickly (like
the test does), the callback will trigger when the game is already busy
with shutting down things.

Fixes #2500