Fix test_platform test
> tmpdir is a py.path.local object […]

This results in `os.path.join()` not working on the `tmpdir` object,
because the `LocalPath` object does not have a method `endswith()`.

  E               AttributeError: 'LocalPath' object has no attribute 'endswith'
  ../../../virtualenv/python3.5.5/lib/python3.5/posixpath.py:84: AttributeError