tests: temporarily fix boatbuilder test failure
Seems we're running into some timing problems here, before greenlets the
test succeeded, now it fails:

    Traceback (most recent call last):
      File "run_uh.py", line 515, in <module>
        main()
      File "run_uh.py", line 268, in main
        ret = horizons.main.start(options)
      File "/home/squiddy/projekte/unknown-horizons/horizons/main.py", line 263, in start
        horizons.globals.fife.run()
      File "/home/squiddy/projekte/unknown-horizons/horizons/engine/engine.py", line 239, in run
        self.loop()
      File "/home/squiddy/projekte/unknown-horizons/horizons/engine/engine.py", line 253, in loop
        f()
      File "/home/squiddy/projekte/unknown-horizons/horizons/timer.py", line 112, in check_tick
        f(self.tick_next_id)
      File "/home/squiddy/projekte/unknown-horizons/horizons/scheduler.py", line 115, in tick
        self._run_additional_jobs()
      File "/home/squiddy/projekte/unknown-horizons/horizons/scheduler.py", line 130, in _run_additional_jobs
        callback.callback()
      File "/home/squiddy/projekte/unknown-horizons/horizons/util/python/callback.py", line 47, in __call__
        return self.callback(*self.args, **self.kwargs)
      File "/home/squiddy/projekte/unknown-horizons/horizons/util/changelistener.py", line 85, in add_change_listener
        self.__listeners.append(listener)
    AttributeError: 'NoneType' object has no attribute 'append'

Need to investigate what changes with the introduction of greenlets.
Perhaps the scheduling works a bit different now and the game engine is
called less often.