Work around #2221 (Crash when loading savegame)
This is not pretty, but I'm not sure a better way can be found easily.
Could not reproduce initially reported problem due to lack of localized
Windows, but a python interpreter session like follows also reproduces:

>>> import time,locale
>>> locale.setlocale(locale.LC_TIME, "zh_TW.EUC-TW")
'zh_TW.EUC-TW'
>>> time.strftime("%A").decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 0:
  invalid continuation byte

Closes #2221