mypy: Remove duplicate class definitions
mypy would complain with:

    horizons/component/inventoryoverlaycomponent.py:196: error: Name 'InventoryOverlayComponent' already defined

At the time of this commit, mypy's unsupported python features [1]
lists:

    Conditional definition of classes (e.g. within if statement)

I can think of two solutions for this issue:

    1. Have mypy ignore it. I checked the issue tracker and there are
       some issues around conditional defines/declarations.
    2. Remove the code in question.

I went with the second option, since we're waiting for for the new FIFE
release with our release, and we can be certain that overlay support is
available.

[1] https://github.com/python/mypy/wiki/Unsupported-Python-Features