Fix hunter_save_load test
Running the session for one second seems to long, since it's possible
that we skip and expected state and jump right to the next one. Which is
what happens here:

    Traceback (most recent call last):
      File "/unknown-horizons/env3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
        self.test(*self.arg)
      File "/unknown-horizons/tests/game/__init__.py", line 258, in wrapped
        return func(*args)
      File "/unknown-horizons/tests/game/test_load_save.py", line 162, in test_hunter_save_load
        await_transition(session, collector, sequence[i], sequence[i+1])
      File "/unknown-horizons/tests/game/test_load_save.py", line 146, in await_transition
        assert collector.state == new_state, "expected new state %s, got %s" % (new_state, collector.state)
    AssertionError: expected new state waiting_for_animal_to_stop, got moving_to_target

The test expected the hunter to wait for the animal, however it already
stopped and the collector was on its way.