Remove overly smart fallback for uninitialized collectors
This was breaking actually legit games in certain cases (namely, when we
tried to save an animalcollector in states.idle, the saving code would
assume that search_job (the continue_action for WildAnimal) would be
assigned as next state when running cancel() here. This resulted in
tracebacks similar to:

  File "horizons/world/units/collectors/collector.py", line 134, in save
    (current_callback, [ str(i) for i in Scheduler().get_classinst_calls
AssertionError: Collector should have callback <bound method Unit[.searc
                h_job of <horizons.world.ingametype.Unit[ object at 0xf6
                da2d0>> scheduled, but has []

Partially reverts commit 2f423e058d94166329e191c9d1841b9d360f7822.