Fix TypeError on ToggleActive assertion
TypeError: cannot concatenate 'str' and 'int' objects
Introduced with 5f97b54df47f8f0c7aa739351166263b39eb78b1.