Fix editor gui test
It failed like this before:

    $ python run_tests.py tests.gui.test_editor:test_save_map -a gui -s
    Traceback (most recent call last):
      ...
      File "/home/reiner/projekte/uh/unknown-horizons/tests/gui/test_editor.py", line 66, in test_save_map
        gui.trigger('menu/button_images/savegameButton')
      ...
      File "/home/reiner/projekte/uh/unknown-horizons/horizons/gui/modules/pausemenu.py", line 94, in _save_game
        self._ingame_gui.show_save_map_dialog()
      File "/home/reiner/projekte/uh/unknown-horizons/horizons/editor/gui.py", line 152, in show_save_map_dialog
        self.message_widget.add('SAVED_GAME')
      File "/home/reiner/projekte/uh/unknown-horizons/horizons/gui/widgets/messagewidget.py", line 104, in add
        sound=sound)
      File "/home/reiner/projekte/uh/unknown-horizons/horizons/gui/widgets/messagewidget.py", line 154, in _add_message
        self.session.ingame_gui.logbook.display_message_history() # update message history on new message
    AttributeError: type object 'Dummy' has no attribute 'display_message_history'

The dummy object works differently now and we need to call it to have a
class instance and not a type.