Fix some import trouble with translation template script
No time to properly investigate what is causing this:

Traceback (most recent call last):
  File "uh/development/extract_strings_from_xml.py", line 40, in <module>
    from horizons.gui.widgets.imagebutton import OkButton, CancelButton, DeleteButton
  File "uh/horizons/gui/__init__.py", line 22, in <module>
    from gui import Gui
  File "uh/horizons/gui/gui.py", line 29, in <module>
    import horizons.main
  File "uh/horizons/main.py", line 46, in <module>
    from horizons.gui import Gui
ImportError: cannot import name Gui